### ISSUE TITLE
Lage mock-data til tpts-tiltakspenger-flate i tpts-tiltakspenger-mottak

### ISSUE THREAD

**Issue by klaramargrethehelgemo** [navikt/tpts-tiltakspenger-mottak#3]

**Comment by pjwalstrom** [comment]
forslag til mockdata ligger her: https://github.com/navikt/tpts-tiltakspenger-mottak/blob/main/src/main/resources/mocksoknad.json

og endepunktet finnes foreløpig på https://tpts-tiltakspenger-mottak.dev.intern.nav.no/mocksoknad
men sikkert lurt å legge under auth

**Comment by pjwalstrom** [comment]
har lagt inn faktisk json-representasjon av søknad nå. Foreslår å lage flere søknader med ulikt innhold og legge til i tpts-tiltakspenger-mottak
